export const GET_TOP_BANNERS = 'GET_TOP_BANNERS';
export const GET_HOT_RECOMMANDED = 'GET_HOT_RECOMMANDED';
export const GET_NEW_ALBUM = 'GET_NEW_ALBUM';
export const GET_UP_RANKING = 'GET_UP_RANKING';
export const GET_NEW_RANKING = 'GET_NEW_RANKING';
export const GET_ORIGIN_RANKING = 'GET_ORIGIN_RANKING';
